pipeline {
    agent any

    environment {
        IMAGE_NAME = "devops-portfolio-app"
        IMAGE_TAG  = "${env.BUILD_NUMBER}"
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials')
    }

   stages {

    stage('Checkout') {
        steps {
            checkout scm
        }
    }

    stage('Install Dependencies') {
        steps {
            dir('app') {
                sh '''
                python3 -m venv venv
                . venv/bin/activate
                pip install -r requirements.txt
                pip install pytest
                '''
            }
        }
    }

    stage('Run Tests') {
        steps {
            dir('app') {
                sh '''
                . venv/bin/activate
                pytest test_app.py --junitxml=test-results.xml
                '''
            }
        }
        post {
            always {
                junit 'app/test-results.xml'
            }
        }
    }

    stage('Build Docker Image') {
        steps {
            sh "docker build -f docker/Dockerfile -t ${IMAGE_NAME}:${IMAGE_TAG} ."
            sh "docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest"
        }
    }

    stage('Push to DockerHub') {
        steps {
            sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            sh "docker push ${IMAGE_NAME}:${IMAGE_TAG}"
            sh "docker push ${IMAGE_NAME}:latest"
        }
    }

    stage('Deploy') {
        steps {
            sh '''
            docker-compose -f docker/docker-compose.yml down || true
            docker-compose -f docker/docker-compose.yml up -d
            '''
        }
    }

}
